"""
Eidolon Vault — Report Generator
========================
Synthesises a ``SimulationLog`` into a ``PredictionReport`` using LLM
analysis.  Saves both ``.txt`` (human‑readable) and ``.json``
(machine‑readable) versions.
"""

from __future__ import annotations

import json
import logging
import os
import re
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, List

from .models import SimulationLog, PredictionReport
from .utils import safe_parse_json, truncate
from .exceptions import EidolonVaultError

if TYPE_CHECKING:
    from .llm_gateway import LLMGateway

logger = logging.getLogger(__name__)

ANALYSIS_SYSTEM = """\
You are a scenario analysis expert. You have just observed a multi‑agent
simulation and must produce a structured prediction report.

RESPOND ONLY WITH VALID JSON:
{
  "summary": "2-3 sentence executive summary of what the simulation revealed",
  "key_findings": [
    "Finding 1 (specific, actionable)",
    "Finding 2",
    "Finding 3"
  ],
  "predictions": [
    {
      "outcome": "Specific predicted outcome",
      "probability": 0.75,
      "rationale": "Why this is likely based on agent behaviors observed"
    }
  ],
  "recommended_actions": [
    "Action 1 — what the user should do based on the simulation",
    "Action 2"
  ],
  "risks": [
    "Risk 1 — what could go wrong",
    "Risk 2"
  ],
  "confidence_overall": 0.7
}

Rules:
- predictions: 2-4 outcomes; probabilities should approximately sum to 1.0
- key_findings: 3-5 specific items
- recommended_actions: 2-4 actionable items
- risks: 2-3 items
- confidence_overall: 0.0–1.0
Return ONLY the JSON object — no markdown, no preamble.\
"""

ANALYSIS_USER = """\
Analyse this completed multi‑agent simulation and produce a prediction report.

SCENARIO: {scenario_title}
AGENTS: {agent_summary}

FULL SIMULATION LOG:
{log_text}

Generate a structured prediction report based on agent behaviours, decisions, and interactions.\
"""

REPORT_TEMPLATE = """\
╔══════════════════════════════════════════════════════════════════╗
║          Eidolon Vault — PREDICTION REPORT                               ║
╚══════════════════════════════════════════════════════════════════╝

Scenario:  {scenario_title}
Run ID:    {run_id}
Hash:      {scenario_hash}
Generated: {generated_at}
Agents:    {agent_count}  |  Turns: {turn_count}  |  Confidence: {confidence_pct}%

──────────────────────────────────────────────────────────────────
EXECUTIVE SUMMARY
──────────────────────────────────────────────────────────────────
{summary}

──────────────────────────────────────────────────────────────────
KEY FINDINGS
──────────────────────────────────────────────────────────────────
{key_findings}

──────────────────────────────────────────────────────────────────
OUTCOME PREDICTIONS
──────────────────────────────────────────────────────────────────
{predictions}

──────────────────────────────────────────────────────────────────
RECOMMENDED ACTIONS
──────────────────────────────────────────────────────────────────
{recommended_actions}

──────────────────────────────────────────────────────────────────
RISKS TO WATCH
──────────────────────────────────────────────────────────────────
{risks}

──────────────────────────────────────────────────────────────────
SIMULATION TRANSCRIPT (last 10 turns)
──────────────────────────────────────────────────────────────────
{transcript}

══════════════════════════════════════════════════════════════════
Generated by Eidolon Vault v1.4 — Persistent Scenario Intelligence Engine
"""


def _repair_truncated_report(raw: str) -> dict:
    """
    Gemini sometimes returns valid JSON that was cut mid-stream when max_tokens
    is just barely too small.  Extract whatever fields arrived intact.
    """
    import re, json
    result = {}
    # Try to pull each top-level string/list field individually
    for field in ("summary", "key_findings", "recommended_actions", "risks"):
        # String fields
        m = re.search(rf'"{field}"\s*:\s*"([^"]+)"', raw, re.DOTALL)
        if m:
            result[field] = m.group(1)
        # Array fields
        m = re.search(rf'"{field}"\s*:\s*(\[[^\]]+\])', raw, re.DOTALL)
        if m:
            try:
                result[field] = json.loads(m.group(1))
            except Exception:
                pass
    # Predictions array
    m = re.search(r'"predictions"\s*:\s*(\[.*?\])', raw, re.DOTALL)
    if m:
        try:
            result["predictions"] = json.loads(m.group(1))
        except Exception:
            pass
    # confidence_overall
    m = re.search(r'"confidence_overall"\s*:\s*([0-9.]+)', raw)
    if m:
        try:
            result["confidence_overall"] = float(m.group(1))
        except Exception:
            pass
    if result:
        import logging
        logging.getLogger(__name__).warning(
            "Report JSON was truncated — salvaged %d field(s) via repair", len(result)
        )
    return result


def _normalise_predictions(preds: list) -> list:
    """Ensure prediction probabilities sum to 1.0."""
    if not preds:
        return preds
    total = sum(float(p.get("probability", 0)) for p in preds)
    if total > 0 and abs(total - 1.0) > 0.05:
        for pred in preds:
            pred["probability"] = round(
                float(pred.get("probability", 0)) / total, 3
            )
    return preds


class ReportGenerator:
    """Generates prediction reports from completed simulation logs."""

    def __init__(self, gateway: "LLMGateway", cfg: dict) -> None:
        self.gateway = gateway
        self.output_dir = Path(os.path.expanduser(cfg["output"]["reports_dir"]))
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, sim_log: SimulationLog) -> PredictionReport:
        """Generate a full ``PredictionReport`` from a ``SimulationLog``."""
        logger.info("Generating report for run %s…", sim_log.run_id)

        log_text = truncate(
            "\n".join(
                f"[Turn {t.turn_number}] {t.agent_name}: {t.response}"
                for t in sim_log.turns
            ),
            4000,
        )
        agent_summary = "\n".join(
            f"  - {a.name} ({a.role}, {a.archetype}): {a.description[:80]}"
            for a in sim_log.agents
        )

        messages = [
            {"role": "system", "content": ANALYSIS_SYSTEM},
            {"role": "user", "content": ANALYSIS_USER.format(
                scenario_title=sim_log.scenario_title,
                agent_summary=agent_summary,
                log_text=log_text,
            )},
        ]

        try:
            raw, _tokens = self.gateway.complete(
                "report_generate", messages,
                # max_tokens intentionally omitted — controlled by
                # task_max_tokens.report_generate in config.yaml
                # (currently 4096 to handle Gemini 2.5 thinking overhead)
                temperature=0.5,
                json_mode=True,
            )
        except Exception as e:
            raise EidolonVaultError(f"Report generation failed: {e}") from e

        # Attempt parse; if truncated JSON, try to salvage what arrived
        data = safe_parse_json(raw)
        if not data.get("summary"):
            data = _repair_truncated_report(raw)

        report = PredictionReport(
            run_id=sim_log.run_id,
            scenario_title=sim_log.scenario_title,
            summary=str(data.get("summary", "No summary generated.")),
            key_findings=[str(f) for f in data.get("key_findings", []) if f],
            predictions=_normalise_predictions(
                [p for p in data.get("predictions", []) if isinstance(p, dict)]
            ),
            recommended_actions=[str(a) for a in data.get("recommended_actions", []) if a],
            risks=[str(r) for r in data.get("risks", []) if r],
            confidence_overall=float(data.get("confidence_overall", 0.5)),
            raw_text=raw,
        )

        self._save(report, sim_log)
        return report

    def render_text(self, report: PredictionReport, sim_log: SimulationLog) -> str:
        """Render the report as a human‑readable text string."""
        key_findings_text = (
            "\n".join(f"  {i+1}. {f}" for i, f in enumerate(report.key_findings))
            or "  (none)"
        )
        predictions_text = (
            "\n".join(
                f"  [{p.get('probability', 0)*100:.0f}%] {p.get('outcome', '?')}\n"
                f"       Rationale: {p.get('rationale', '')}"
                for p in report.predictions
            )
            or "  (none)"
        )
        actions_text = (
            "\n".join(f"  → {a}" for a in report.recommended_actions)
            or "  (none)"
        )
        risks_text = (
            "\n".join(f"  ⚠ {r}" for r in report.risks)
            or "  (none)"
        )
        transcript = "\n".join(
            f"  [T{t.turn_number}] {t.agent_name}: "
            f"{t.response[:120]}{'…' if len(t.response) > 120 else ''}"
            for t in sim_log.turns[-10:]
        )

        return REPORT_TEMPLATE.format(
            scenario_title=report.scenario_title,
            run_id=report.run_id,
            scenario_hash=sim_log.scenario_hash,
            generated_at=report.generated_at[:19],
            agent_count=len(sim_log.agents),
            turn_count=len(sim_log.turns),
            confidence_pct=int(report.confidence_overall * 100),
            summary=report.summary,
            key_findings=key_findings_text,
            predictions=predictions_text,
            recommended_actions=actions_text,
            risks=risks_text,
            transcript=transcript,
        )

    def _save(self, report: PredictionReport, sim_log: SimulationLog) -> Path:
        safe_title = re.sub(r"[^\w\-]", "_", report.scenario_title)
        safe_title = re.sub(r"_+", "_", safe_title).strip("_")[:40] or "report"

        try:
            ts = datetime.fromisoformat(report.generated_at).strftime("%Y%m%d_%H%M%S")
        except ValueError:
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")

        base = f"report_{safe_title}_{ts}"
        self.output_dir.mkdir(parents=True, exist_ok=True)
        txt_path  = self.output_dir / f"{base}.txt"
        json_path = self.output_dir / f"{base}.json"

        rendered = self.render_text(report, sim_log)
        txt_path.write_text(rendered, encoding="utf-8")
        json_path.write_text(
            json.dumps(report.to_dict(), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )

        logger.info("Report saved: %s", txt_path)
        return txt_path
